# Generated by CMake

# Protect against multiple inclusion
if(TARGET odfaeg::odfaeg-core)
    return()
endif()

# Compute installation prefix
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)

# Core
add_library(odfaeg::odfaeg-core STATIC IMPORTED)
set_target_properties(odfaeg::odfaeg-core PROPERTIES
    IMPORTED_LOCATION "${_IMPORT_PREFIX}/lib/libodfaeg-core.a"
    INTERFACE_INCLUDE_DIRECTORIES 
    "${_IMPORT_PREFIX}/include"
    "${_IMPORT_PREFIX}/include/odfaeg/external"
)

# Math
add_library(odfaeg::odfaeg-math STATIC IMPORTED)
set_target_properties(odfaeg::odfaeg-math PROPERTIES
    IMPORTED_LOCATION "${_IMPORT_PREFIX}/lib/libodfaeg-math.a"
    INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
    INTERFACE_LINK_LIBRARIES odfaeg::odfaeg-core
)

# Entity
add_library(odfaeg::odfaeg-entity STATIC IMPORTED)
set_target_properties(odfaeg::odfaeg-entity PROPERTIES
    IMPORTED_LOCATION "${_IMPORT_PREFIX}/lib/libodfaeg-entity.a"
    INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
    INTERFACE_LINK_LIBRARIES "odfaeg::odfaeg-math;odfaeg::odfaeg-core"
)

# Physics
add_library(odfaeg::odfaeg-physics STATIC IMPORTED)
set_target_properties(odfaeg::odfaeg-physics PROPERTIES
    IMPORTED_LOCATION "${_IMPORT_PREFIX}/lib/libodfaeg-physics.a"
    INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
    INTERFACE_LINK_LIBRARIES "odfaeg::odfaeg-entity;odfaeg::odfaeg-math;odfaeg::odfaeg-core"
)

# Window
add_library(odfaeg::odfaeg-window STATIC IMPORTED)
set_target_properties(odfaeg::odfaeg-window PROPERTIES
    IMPORTED_LOCATION "${_IMPORT_PREFIX}/lib/libodfaeg-window.a"
    INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
    INTERFACE_LINK_LIBRARIES "odfaeg::odfaeg-physics;odfaeg::odfaeg-entity;odfaeg::odfaeg-math;odfaeg::odfaeg-core"
)

# Graphics
add_library(odfaeg::odfaeg-graphics STATIC IMPORTED)
set_target_properties(odfaeg::odfaeg-graphics PROPERTIES
    IMPORTED_LOCATION "${_IMPORT_PREFIX}/lib/libodfaeg-graphics.a"
    INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
    INTERFACE_LINK_LIBRARIES "odfaeg::odfaeg-window;odfaeg::odfaeg-physics;odfaeg::odfaeg-entity;odfaeg::odfaeg-math;odfaeg::odfaeg-core"
)

# Base
add_library(odfaeg::odfaeg-base INTERFACE IMPORTED)
set_target_properties(odfaeg::odfaeg-base PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES 
    "${_IMPORT_PREFIX}/include"    
)
