set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

# Compilateurs MSYS2
set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)

# Préfixe MSYS2
set(MSYS2_PREFIX "C:/msys64/mingw64")

set(CMAKE_PREFIX_PATH "C:/Program Files (x86)/ODFAEG")
set(CMAKE_FIND_ROOT_PATH "${MSYS2_PREFIX}")

# Trouver les libs dans MSYS2
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# Pour libc++
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -stdlib=libc++")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -stdlib=libc++")