#version 460
layout(binding = 0, r32ui) uniform readonly uimage2D srcMip;
layout(binding = 1, r32ui) uniform writeonly uimage2D dstMip;
void main() {
    ivec2 gid = ivec2(gl_GlobalInvocationID.xy);

    // Lire 4 pixels du mip courant
    uint d00 = imageLoad(srcMip, gid * 2 + ivec2(0,0)).r;
    uint d10 = imageLoad(srcMip, gid * 2 + ivec2(1,0)).r;
    uint d01 = imageLoad(srcMip, gid * 2 + ivec2(0,1)).r;
    uint d11 = imageLoad(srcMip, gid * 2 + ivec2(1,1)).r;

    // Reversed-Z → on prend le MIN
    uint d = max(max(d00, d10), max(d01, d11));

    imageStore(dstMip, gid, uvec4(d));
}