#version 460
#extension GL_EXT_debug_printf : enable
#define MAX_BONE_INFLUENCE 4
#define MAX_BONES 100 
#define NB_PRIMITIVE_TYPES 6
#define MAX_FRAMES_IN_FLIGHT 2
#define MAX_BONES_INFLUENCE 4
#define MAX_VERTICES 255
#define MAX_PRIMITIVES 85
/*Boîtes englobantes des objets*/
struct AABB {
	vec3 center;
	vec3 size;
};
/*Objets*/
struct Object {
	AABB globalBounds;
	int id;	
	int type;                             
	int subMeshesOffset;
	int modelDataOffset;		   
	int nbSubMeshes;
	int renderingType;
};
struct LODLevel {
    int index_offset;
    int index_count;
    int meshletOffset;
    int meshletCount;
};
/*subMesh*/
struct SubMesh {
	AABB globalBounds;
	int vertexOffset;
	int indexOffset;
	int primitiveType;
	int materialId;
	int nbVertices;
	int nbIndexes;
	int lodOffset;
	int id;
    int lodLevel;
    int objectId;
    int clusterOffset;
    int clusterCount;
};
struct Cluster {
    AABB globalBounds;
    int meshletOffset;
    int meshletCount;
    int id;
    int lodLevel;
};
/*Matrices*/
struct ModelData {
	mat4 modelMatrix;
	mat4 shadowProjMatrix;
	mat4 borderMatrices;
};  
struct Offset {
    int previousOffsetHeight;
    int offsetHeight;
    int meshletOffset;
};      
/*Matériaux*/
struct MaterialData {   
    uint diffuseTextureIndex;
    uint specularTextureIndex;
    uint normalTextureIndex;
    uint metalnessTextureIndex;
    uint roughnessTextureIndex;
    uint aoTextureIndex;
    uint emissiveTextureIndex;
    uint materialType;
    uint instanceId;   
    uint nbVertices;
    uint nbIndexes;
    int instanceGroupId;
    uint vertsInstanceSet;
    uint materialId;
    uint nbBuffers;
    int reflectable;
    int refractable;  
};
struct MeshDrawCommand {
    uint groupXCount;
    uint groupYCount;
    uint groupZCount;
};
struct TaskData {
    MeshDrawCommand meshDrawCommand;
    uint instanceBase; 
    int clusterId;  
    int offsetHeight;
    uint heightCount; 
};
struct Vertex {
    vec3 position; ///< 3D position of the vertex
    uint color; ///< Color of the vertex
    vec2 texCoords; ///< Coordinates of the texture's pixel to map to the vertex
    vec3 normal;
    //bone indexes which will influence this vertex
    int m_BoneIDs[MAX_BONES_INFLUENCE];
    //weights from each bone
    float m_Weights[MAX_BONES_INFLUENCE];
    int submeshId;
};
struct GridCell {
    int clusterId;
};
struct Cluster {
    AABB globalBounds;
    uint id;
    uint children[8];
    uint leaf;
    uint meshletCount;
    uint meshetOffset;
    uint lod;
};
/*objets en entrée.*/
layout(push_constant) uniform PushConstant {    
    uint currentFrame;
    uint totalHeightCount;
    vec3 gridCellSize;
    vec3 nbCellsPerRow;
    uint clustersCount;
} pc;
layout (set = 0, binding = 0) buffer ObjectTypesSSBO {
	int types[];
} objectTypes[MAX_FRAMES_IN_FLIGHT];
layout (std430, set = 0, binding = 1) buffer inputObjectSSBO {
	Object objects[];
} inputObjectBuffer;
/*SubMeshes en entrée.*/
layout (std430, set = 0, binding = 2) buffer inputSubmeshesSSBO {
	SubMesh subMeshes[];
} inputSubmeshesBuffer;
layout (std430, set = 0, binding = 3) buffer inputClusterSSBBO {
    Cluster clusters[];
} inputClustersBuffer;
/*matrices en entrée.*/
layout (std430, set = 0, binding = 4) buffer inputModelDataSSBO {
	ModelData modelData[];
} inputModelData;
/*matériaux en entrée.*/
layout (std430, set = 0, binding = 5) buffer inputMaterialDataSSBO {
	MaterialData materialData[];
} inputMaterialData[NB_PRIMITIVE_TYPES*MAX_FRAMES_IN_FLIGHT];
/*matériaux en sortie.*/
layout (std430, set = 0, binding = 6) buffer outputMaterialDataSSBO {
	MaterialData materialData[];
} outputMaterialData[NB_PRIMITIVE_TYPES*MAX_FRAMES_IN_FLIGHT];
/*matrices des objets visibles pour les instances en sortie.*/
layout (std430, set = 0, binding = 7) buffer outputModelDataSSBO {
	ModelData modelData[];
} outputModelData[NB_PRIMITIVE_TYPES*MAX_FRAMES_IN_FLIGHT];
/*Matrices des objets visible en sortie pour les non instances*/
layout (std430, set = 0, binding = 8) buffer outputMeshDataSSBO {
	SubMesh meshData[];
} outputMeshData[NB_PRIMITIVE_TYPES*MAX_FRAMES_IN_FLIGHT];
/*position dans le buffer de matrices de sortie pour les instance*/
layout (std430, set = 0, binding = 9) buffer offsetInOutputModelDataSSBO {
	uint modelDataOffset;
} offsetInOutputModelData[NB_PRIMITIVE_TYPES*MAX_FRAMES_IN_FLIGHT];
/*position dans le buffer des matrices de sortie*/
layout (std430, set = 0, binding = 11) buffer offsetInOutputMeshDataSSBO {
	uint meshDataOffset;
} offsetInOutputMeshData[NB_PRIMITIVE_TYPES*MAX_FRAMES_IN_FLIGHT];
/*Nombre de commandes pour le rendu indirect.*/
layout (std430, set = 0, binding = 12) buffer outputTaskCountSSBO {
	uint taskCount;
} outputTaskCount[NB_PRIMITIVE_TYPES*MAX_FRAMES_IN_FLIGHT];
layout (std430, set = 0, binding = 13) buffer outputTaskDataSSBO {
	TaskData taskData[];
} outputTaskData[NB_PRIMITIVE_TYPES*MAX_FRAMES_IN_FLIGHT];
/*position dans le buffer de commandes pour le rendu indirect.*/
layout (std430, set = 0, binding = 14) buffer offsetInOutputTaskDataSSBO {
	uint offsetTaskData;
} offsetInOutputTaskData[NB_PRIMITIVE_TYPES*MAX_FRAMES_IN_FLIGHT];
/*Buffer pour données de la frame*/
layout (std430, set = 0, binding = 15) buffer offsetOutputMaterialSSBO {
	uint materialOffset;
} offsetInOutputMaterial[NB_PRIMITIVE_TYPES*MAX_FRAMES_IN_FLIGHT];
layout (std430, set = 0, binding = 16) buffer outputInstanceBaseSSBO {
	uint instanceBase;
} outputInstanceBase[NB_PRIMITIVE_TYPES*MAX_FRAMES_IN_FLIGHT];
layout (std140, set = 0, binding = 17) uniform UniformBufferObject {
	AABB frustrum;			
	uint nbObjectTypes;
	uint paddings[3];
} ubo[MAX_FRAMES_IN_FLIGHT];
layout (std430, set=0, binding = 18) buffer LodLevelBuffer {
    LODLevel lodLevel[];
} lodLevelData;
layout (std430, set = 0, binding = 19) buffer offsetBuffer {
    Offset offsets;
} offsetsData[NB_PRIMITIVE_TYPES*MAX_FRAMES_IN_FLIGHT];
layout (std430, set = 0, binding = 20) buffer vertexBufferSSBO {
    Vertex vertices[];
} vertexData[NB_PRIMITIVE_TYPES];
layout (std430, set = 0, binding = 21) buffer outputHeight {
    Vertex vertices[];
} outputVertices[MAX_FRAMES_IN_FLIGHT];
layout (std430, set = 0, binding = 22) buffer inputClusterSSBBO {
    GridCell grid[];
} inputGridBuffer;
layout (std430, set = 0, binding = 23) buffer outputMeshletSSBO {
    Meshlet meshlets[];
} inputMeshlet;
layout (std430, set = 0, binding = 24) buffer outputMeshletSSBO {
    Meshlet meshlets[];
} outputMeshlet[NB_PRIMITIVE_TYPES*MAX_FRAMES_IN_FLIGHT];
layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
bool intersects (AABB first, AABB second) {
    float hx1 = first.size.x * 0.5;
    float hy1 = first.size.y * 0.5;
    float hz1 = first.size.z * 0.5;
    float hx2 = second.size.x * 0.5;
    float hy2 = second.size.y * 0.5;
    float hz2 = second.size.z * 0.5;
    //Check the mins and max medians positions.
    float minX1 = first.center.x - hx1;
    float minX2 = second.center.x - hx2;
    float minY1 = first.center.y - hy1;
    float minY2 = second.center.y - hy2;
    float minZ1 = first.center.z - hz1;
    float minZ2 = second.center.z - hz2;
    float maxX1 = first.center.x + hx1;
    float maxX2 = second.center.x + hx2;
    float maxY1 = first.center.y + hy1;
    float maxY2 = second.center.y + hy2;
    float maxZ1 = first.center.z + hz1;
    float maxZ2 = second.center.z + hz2;
    //If the medians overlap, our two boxes intersects.
    for (int i = 0; i < 3; i++) {
        if (i == 0) {
            if (minX1 > maxX2 || maxX1 < minX2)
                return false;
        } else if (i == 1) {
            if (minY1 > maxY2 || maxY1 < minY2)
                return false;
        } else {
            if (minZ1 > maxZ2 || maxZ1 < minZ2)
                return false;
        }
    }
    return true;
}
bool hasNeighbour(vec3 pos, int axe) {
    vec3 offset;
    if (axe == 0) {
        offset = vec3(pos.x - pc.gridCellSize.x, pos.y, pos.z);
    } else if (axe == 1) {
        offset = vec3(pos.x + pc.gridCellSize.x, pos.y, pos.z);
    } else if (axe == 2) {
        offset = vec3(pos.x, pos.y - pc.gridCellSize.y, pos.z);
    } else if (axe == 3) {
        offset = vec3(pos.x, pos.y + pc.gridCellSize.y, pos.z);
    } else if (axe == 4) {
        offset = vec3(pos.x, pos.y, pos.z - pc.gridCellSize.z);
    } else {
        offset = vec3(pos.x, pos.y, pos.z + pc.gridCellSize.z);
    }
    int cellId = (offset.x / pc.gridCellSize.x) + (offset.y / pc.gridCellSize.y) * pc.nbCellsPerRow.x + (offset.z / pc.gridCellSize.z) * pc.nbCellsPerRow.y;
    return (cellId != -1);
}
void setMeshletsFromBox(AABB frustrum, int lod, Object object, SubMesh sm, int f, inout TaskData taskData) {   
    uint stack[32]; 
    uint sp = 0;    
    uint tmpX = frustrum.center.x - frustrum.size.x * 0.5;
    uint tmpY = frustrum.center.y - frustrum.size.y * 0.5;
    uint tmpZ = frustrum.center.z - frustrum.size.z * 0.5;
    for (uint i = tmpX; i < (frustrum.center.x - frustrum.size.x*0.5) + frusturm.size.x; i+= pc.gridCellSize.x) {
        for (uint j = tmpY; j < (frustrum.center.y - frustrum.size.y*0.5) + frusturm.size.y; j+= pc.gridCellSize.y) {
            for (uint k = tmpZ; k < (frustrum.center.z - frustrum.size.z*0.5) + frusturm.size.z; k+= pc.gridCellSize.z) {
                //Root.
                int cellId = (tmpX / pc.gridCellSize.x) + (tmpY / pc.gridCellSize.y) * pc.nbCellsPerRow.x + (tmpZ / pc.gridCellSize.z) * pc.nbCellsPerRow.y;
                if (cellId < pc.clustersCount) {
                    stack[sp++] = inputClustersBuffer.clusters[inputGridBuffer.grid[cellId].clusterId].id;
                    //Case non vide.
                    if (stack[sp] != -1) {
                        while (sp > 0) {
                            uint id = stack[sp--];
                            Cluster n = nodes[id];
                            if (!intersects(frustrum, n.globalBounds)) {
                                continue;
                            }
                            if (n.leaf) {
                                if (n.lod == lod && n.id ==  sm.clusterId) {
                                    
                                    
                                    taskData.meshletCount = n.meshletCount;
                                    uint clusterOffset = atomicAdd(offsetsData[pc.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.clusterOffest, 1);                        
                                    outputClusters[pc.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].clusters[clusterOffset] = cluster;  
                                    //Cluster de modèle 3D visible : On dessine ce qu'il contient.
                                    if (object.renderType == 0) {
                                        taskData.meshDrawCommand.y++;                             
                                    } else if (objectType == 1) {
                                        //Height visible : on le génère.
                                        for (uint h = 0; h < 4; h++) {
                                            uint offset = atomicAdd(offsetsData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.verticesOffset, 1); 
                                            vertices[offset] = inputHeightsData.heights[sm.vertexOffset+i];
                                            taskData.heightCount++;
                                        }
                                        //Voxel. 
                                    } else {
                                        //Voxel visible : on le génère.
                                        if (hasNeighbour(vec3(tmpX, tmpY, tmpZ), f)) {
                                            uint count = offsets.offsetVoxel - offsets.previousOffsetVoxel;
                                            //Si on dépasse on créé une nouvelle tâche.
                                            if (count + 4 >= MAX_VERTICES 
                                                || (count + 4) / 4 * 2 >= MAX_PRIMITIVES 
                                                || offsets.offsetVoxel + count == pc.totalVoxelCount-1) {                        
                                                TaskData taskData; 
                                                MeshDrawCommand meshDrawCommand;                        
                                                meshDrawCommand.groupXCount = 1;
                                                meshDrawCommand.groupYCount = 1;
                                                meshDrawCommand.groupZCount = 1;                     
                                                taskData.clusterOffset = atomicAdd(offsetsData[pc.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.clusterOffest, 1);
                                                taskData.meshDrawCommand = meshDrawCommand;                      
                                                taskData.voxelOffset = offsets.previousOffsetHeight;
                                                uint taskDataOffset = atomicAdd(outputTaskCount[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskCount, 1);
                                                outputTaskData[subMesh.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskData[taskDataOffset] = taskData; 
                                                offsets.previousOffsetVoxel = offsets.offsetVoxel;                    
                                            } 
                                            
                                            for (uint v = 0; v < 4; v++) {
                                                uint offset = atomicAdd(offsetsData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.verticesOffset, 1); 
                                                vertices[offset] = inputHeightsData.heights[sm.vertexOffset+i];
                                                taskData.offsetVoxel++;
                                            }
                                        }    
                                    }
                                }                          
                            } else {
                                for (uint c = 0; c < 8; c++) {
                                    stack[sp++] = n.children[c].id;
                                }
                            } 
                        }
                    }
                }
            }
        }
    }
}
void main() {
    //debugPrintfEXT("nb object types : %i, %i, %i",gl_GlobalInvocationID.x, gl_GlobalInvocationID.y, gl_GlobalInvocationID.z);
    memoryBarrier();
    //SubMesh subMesh = inputSubmeshesBuffer.subMeshes[gl_GlobalInvocationID.x];
    Object object = inputObjectBuffer.objects[gl_GlobalInvocationID.x];
	uint materialId = gl_GlobalInvocationID.y;
	uint primitiveType = gl_GlobalInvocationID.z;

	//debugPrintfEXT("nb object types : %v3f, %v3f, %i",ubo[pc.currentFrame].frustrum.center, ubo[pc.currentFrame].frustrum.size, ubo[pc.currentFrame].nbObjectTypes);
	
	for (uint t = 0; t < ubo[pc.currentFrame].nbObjectTypes; t++) {
	    //debugPrintfEXT("type : %i,%i", t, object.type );
        //Modèles 3D. (Regroupement par instances)
		if (object.type == objectTypes[pc.currentFrame].types[t] && intersects(object.globalBounds, ubo[pc.currentFrame].frustrum)) {
		    if (object.renderingType == 0) {
                //debugPrintfEXT("Object in frustrum");			
                //Regroupement des données par matériaux et par type de primitive. (Batching)
                for (uint s = 0; s < object.nbSubMeshes; s++) {                    
                    SubMesh subMesh = inputSubmeshesBuffer.subMeshes[object.subMeshesOffset+s]; 

                    if (subMesh.materialId == materialId && subMesh.primitiveType == primitiveType && intersects(subMesh.globalBounds, ubo[pc.currentFrame].frustrum)) {
                        //debugPrintfEXT("submesh in frustrum %i", s);
                        float dist = distance(ubo[pc.currentFrame].frustrum.center, subMesh.globalBounds.center);
                        float lodStep = 20.0;
                        int lod = clamp(int(dist / lodStep), 0, 4);
                        subMesh.lodLevel = lod;
                        uint taskDataOffset = inputMaterialData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId].materialSet;   
                        /*Matériel instanciable.*/
                        if (inputMaterialData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId].instanceGroupId != -1) {
                            /*Nouvelle instance de matériel/primitive visible = nouvelle tâche et on enregistre l'offset de la tâche,
                            pour les instances visibles suivantes.*/
                            if(inputMaterialData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId].taskOffsetSet == 0) {
                                    
                                inputMaterialData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId].taskOffsetSet = 1;
                                uint taskDataOffset = atomicAdd(outputTaskCount[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskCount, 1);
                                uint instanceId = atomicAdd(outputInstanceBase[NB_PRIMITIVE_TYPES*MAX_FRAMES_IN_FLIGHT].instanceBase, 1);
                                
                                inputMaterialData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId].taskOffset = taskDataOffset;
                                MeshDrawCommand meshDrawCommand;
                                meshDrawCommand.groupXCount = 0;
                                meshDrawCommand.groupYCount = 0;
                                meshDrawCommand.groupZCount = 8;
                                TaskData taskData;
                                taskData.baseInstance = instanceId;
                                taskData.heightCount = 0;
                                taskData.clusterOffset = offsetsData[pc.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.clusterOffest;
                                taskData.meshDrawCommand = meshDrawCommand; 
                                MaterialData material = inputMaterialData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId];
                                material.materialId = materialId;
                                outputTaskData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskData[taskDataOffset] = taskData;
                                outputMaterialData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[instanceId] = material;
                                uint offsetInOutputMeshData = atomicAdd(offsetInOutputMeshData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].meshDataOffset, 1);
                                outputMeshData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].meshData[instanceId]  = subMesh;
                                setVisibleMesheltsFromBox(frustrum, lod, object, sm, s, taskData);
                            }
                            uint taskOffset = inputMaterialData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId].taskOffset;
                            uint baseInstance = outputInstanceBase[NB_PRIMITIVE_TYPES*MAX_FRAMES_IN_FLIGHT].instanceBase;
                            uint instanceId = baseInstance + outputTaskData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskData[taskDataOffset].meshDrawCommand.groupXCount;
                            ModelData modelData = inputModelData.modelData[object.modelDataOffset];
                            outputModelData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].modelData[instanceId] = modelData;
                            //nombre d'instances + 1.                           
                            outputTaskData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskData[taskDataOffset].meshDrawCommand.groupXCount++;
                        }
                        //Matériel non instanciable.                                               
                    } else {                        
                        uint offsetTaskData = atomicAdd(outputTaskCount[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskCount, 1);
                        uint instanceId = atomicAdd(outputInstanceBase[NB_PRIMITIVE_TYPES*MAX_FRAMES_IN_FLIGHT].instanceBase, 1);
                        MeshDrawCommand meshDrawCommand;                        
                        meshDrawCommand.groupXCount = 1;
                        meshDrawCommand.groupYCount = 0;
                        meshDrawCommand.groupZCount = 8;
                        TaskData taskData;
                        taskData.baseInstance = instanceId;
                        taskData.heightCount = 0;
                        taskData.clusterOffset = offsetsData[pc.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.clusterOffest;
                        taskData.meshDrawCommand = meshDrawCommand;
                        //debugPrintfEXT("lod infos : %i, %i",subMesh.lodLevel[lod].index_offset,subMesh.lodLevel[lod].index_count);
                        //debugPrintfEXT("instance base %i", instanceBase); 
                        outputTaskData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskData[offsetTaskData] = taskData;
                        //debugPrintfEXT("indirect elements draw command offset : %i", indirectElementsDrawCommandOffset);
                        ModelData modelData = inputModelData.modelData[object.modelDataOffset];
                        //debugPrintfEXT("model data matrix : %v4f\n%v4f\n%v4f\n%v4f", modelData.modelMatrix[0], modelData.modelMatrix[1], modelData.modelMatrix[2], modelData.modelMatrix[3]);
                        //debugPrintfEXT("object data offset : %i",objectDataOffset);
                        outputModelData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].modelData[instanceId] = modelData;
                        //debugPrintfEXT("offsets : %i, %i, %i", objectDataOffset, offsetInOutputMaterial, indirectElementsDrawCommandOffset);
                        MaterialData material = inputMaterialData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId];
                        //debugPrintfEXT("texture id : %i", material.diffuseTextureIndex);
                        material.materialId = materialId;
                        //debugPrintfEXT("culling shader draw id : %i, material id : %i", indirectElementsDrawCommandOffset, materialId);
                        //debugPrintfEXT("instance base : %i", instanceBase);
                        
                        outputMaterialData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[instanceId] = material;
                        uint offsetInOutputMeshData = atomicAdd(offsetInOutputMeshData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].meshDataOffset, 1);
                        outputMeshData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].meshData[instanceId]  = subMesh;
                        //debugPrintfEXT("material datas %v2f", material.uvScale);
                        //debugPrintfEXT("Output Model Matrix : %i\n%v4f\n%v4f\n%v4f\n%v4f",objectDataOffset,outputObjectData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].objectData[objectDataOffset].modelMatrix[0], outputObjectData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].objectData[objectDataOffset].modelMatrix[1], outputObjectData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].objectData[objectDataOffset].modelMatrix[2], outputObjectData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].objectData[objectDataOffset].modelMatrix[3]);
                        setVisibleMesheltsFromBox(frustrum, lod, object, sm, s, taskData);
                    }           
                } 
            }
        //Heighmap : Regroupement des tâches par limite de sommets dans ce cas.
        } else if (object.renderingType == 1) {
            for (uint s = 0; s < object.nbSubMeshes; s++) {
                SubMesh square = inputSubmeshesBuffer.subMeshes[object.subMeshesOffset+s];
                if (subMesh.materialId == materialId && subMesh.primitiveType == primitiveType && intersects(subMesh.globalBounds, ubo[pc.currentFrame].frustrum)) { 
                    float dist = distance(ubo[pc.currentFrame].frustrum.center, square.globalBounds.center);
                    float lodStep = 20.0;
                    int lod = clamp(int(dist / lodStep), 0, 4);
                    subMesh.lodLevel = lod;               
                    uint count = offsets.offsetHeight - offsets.previousOffsetHeight;
                    //Si on dépasse on créé une nouvelle tâche.
                    if (count + 4 >= MAX_VERTICES 
                        || (count + 4) / 4 * 2 >= MAX_PRIMITIVES 
                        || offsets.offsetHeight + count == pc.totalHeightCount-1) {                        
                        TaskData taskData; 
                        MeshDrawCommand meshDrawCommand;                        
                        meshDrawCommand.groupXCount = 1;
                        meshDrawCommand.groupYCount = 1;
                        meshDrawCommand.groupZCount = 1;                     
                        taskData.clusterOffset = atomicAdd(offsetsData[pc.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.clusterOffest, 1);
                        taskData.meshDrawCommand = meshDrawCommand;                      
                        taskData.heightCount = count;
                        uint taskDataOffset = atomicAdd(outputTaskCount[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskCount, 1);
                        outputTaskData[subMesh.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskData[taskDataOffset] = taskData; 
                        offsets.previousOffsetHeight = offsets.offsetHeight;                    
                    } 
                    setVisbleMeshletsFromBox(frustrum, lod, object, square, s, taskData);  
                }                      
            }
        } else {
            for (uint s = 0; s < object.nbSubMeshes; s++) {
                SubMesh face = inputSubmeshesBuffer.subMeshes[object.subMeshesOffset+s];
                if (subMesh.materialId == materialId && subMesh.primitiveType == primitiveType && intersects(subMesh.globalBounds, ubo[pc.currentFrame].frustrum)) { 
                    float dist = distance(ubo[pc.currentFrame].frustrum.center, square.globalBounds.center);
                    float lodStep = 20.0;
                    int lod = clamp(int(dist / lodStep), 0, 4);
                    subMesh.lodLevel = lod;  
                    setVisbleMeshletsFromBox(frustrum, lod, object, square, s, taskData);  
                }                      
            }
        }
	}
}