#version 460
#extension GL_EXT_debug_printf : enable
#define MAX_BONE_INFLUENCE 4
#define MAX_BONES 100 
#define NB_PRIMITIVE_TYPES 6
#define MAX_FRAMES_IN_FLIGHT 2
#define MAX_BONES_INFLUENCE 4
#define MAX_VERTICES 255
#define MAX_PRIMITIVES 85
/*Boîtes englobantes des objets*/
struct AABB {
	vec3 center;
	vec3 size;
};
/*Objets*/
struct Object {
	AABB globalBounds;
	int id;	
	int type;                             
	int subMeshesOffset;
	int modelDataOffset;		   
	int nbSubMeshes;
	int renderingType;
    //int paddings[2];
};
struct LODLevel {
    int index_offset;
    int index_count;
    int meshletOffset;
    int meshletCount;
};
/*subMesh*/
struct SubMesh {
	AABB globalBounds;
	int vertexOffset;
	int indexOffset;
	int primitiveType;
	int materialId;
	int nbVertices;
	int nbIndexes;
	int lodOffset;
	int id;
    int lodLevel;
    int objectId;   
};
/*Matrices*/
struct ModelData {
	mat4 modelMatrix;
	mat4 shadowProjMatrix;
	mat4 borderMatrices;
};  
struct Offset {
    uint previousOffsetVertex;
    uint offsetVertex;    
    uint instanceOffset;
    uint clusterOffset;
    uint submeshOffset;
    uint offsetTaskData;
};      
/*Matériaux*/
struct MaterialData {   
    uint diffuseTextureIndex;
    uint specularTextureIndex;
    uint normalTextureIndex;
    uint metalnessTextureIndex;
    uint roughnessTextureIndex;
    uint aoTextureIndex;
    uint emissiveTextureIndex;
    uint materialType;
    uint instanceId;   
    uint nbVertices;
    uint nbIndexes;
    int instanceGroupId;
    uint vertsInstanceSet;
    uint taskOffset;
    uint materialId;
    uint nbBuffers;
    int opaque;
    int reflectable;
    int refractable;
};
struct MeshDrawCommand {
    uint groupXCount;
    uint groupYCount;
    uint groupZCount;
};
struct TaskData {
    MeshDrawCommand meshDrawCommand;
    uint baseInstance;    
    uint vertexCount;
    uint primitiveCount;
    uint vertexOffset; 
    uint clusterOffset;
};
struct Vertex {
    vec3 position; ///< 3D position of the vertex
    uint color; ///< Color of the vertex
    vec2 texCoords; ///< Coordinates of the texture's pixel to map to the vertex
    vec3 normal;
    //bone indexes which will influence this vertex
    int m_BoneIDs[MAX_BONES_INFLUENCE];
    //weights from each bone
    float m_Weights[MAX_BONES_INFLUENCE];
    int submeshId;
};
struct GridCell {
    AABB volume;
    int clusterId;
    int clusterOffset;
    int clusterCount;    
};
struct Cluster {
    AABB volume;
    int meshletOffset;
    int meshletCount;
    int id;
    int lod;
    int leaf;	
    int submeshId;			
    //int children[8];    
};
struct MeshLet {
    uint id;
    uint vertexOffset;
    uint indexOffset;
    uint nbVertices;
    uint nbIndexes; 
    uint minVertex;
    uint maxVertex;     
    int clusterId;     
    uint lod;
    int voxel;
    int rendered;
    int pad;
    vec3 mins;
    vec3 maxs; 
};
/*objets en entrée.*/
layout(push_constant) uniform PushConstant {    
    uint currentFrame;    
} pc;
layout (std430, set = 0, binding = 0) buffer inputObjectSSBO {
	Object objects[];
} inputObjectBuffer;
/*SubMeshes en entrée.*/
layout (std430, set = 0, binding = 1) buffer inputSubmeshesSSBO {
	SubMesh subMeshes[];
} inputSubmeshesBuffer;
layout (std430, set = 0, binding = 2) buffer inputClusterSSBBO {
    Cluster clusters[];
} inputClustersBuffer;
layout (std430, set = 0, binding = 3) buffer GirdSSBBO {
    GridCell grid[];
} inputGridBuffer;
/*matrices en entrée.*/
layout (std430, set = 0, binding = 4) buffer inputModelDataSSBO {
	ModelData modelData[];
} inputModelData;
/*matériaux en entrée.*/
layout (std430, set = 0, binding = 5) buffer inputMeshletSSBO {
    MeshLet meshlets[];
} inputMeshlet;
layout (std430, set=0, binding = 6) buffer LodLevelBuffer {
    LODLevel lodLevel[];
} lodLevelData;
layout (std430, set = 0, binding = 7) buffer inputVertexSSBO {
    Vertex vertices[];
} inputVertices[NB_PRIMITIVE_TYPES];
layout (std430, set = 0, binding = 8) buffer inputMaterialDataSSBO {
	MaterialData materialData[];
} inputMaterialData[NB_PRIMITIVE_TYPES*MAX_FRAMES_IN_FLIGHT];
//Clusters visibles.
layout (std430, set = 0, binding = 9) buffer outputClusterSSBO {
	Cluster clusters[];
} outputClusters[NB_PRIMITIVE_TYPES*MAX_FRAMES_IN_FLIGHT];
/*matrices des objets visibles pour les instances en sortie.*/
layout (std430, set = 0, binding = 10) buffer outputModelDataSSBO {
	ModelData modelData[];
} outputModelData[NB_PRIMITIVE_TYPES*MAX_FRAMES_IN_FLIGHT];
/*Matrices des objets visible en sortie pour les non instances*/
layout (std430, set = 0, binding = 11) buffer outputMeshDataSSBO {
	SubMesh meshData[];
} outputMeshData[NB_PRIMITIVE_TYPES*MAX_FRAMES_IN_FLIGHT];
/*position dans le buffer des matrices de sortie*/
layout (std430, set = 0, binding = 12) buffer outputTaskCountSSBO {
	uint taskCount;
} outputTaskCount[NB_PRIMITIVE_TYPES*MAX_FRAMES_IN_FLIGHT];
layout (std430, set = 0, binding = 13) buffer outputTaskDataSSBO {
	TaskData taskData[];
} outputTaskData[NB_PRIMITIVE_TYPES*MAX_FRAMES_IN_FLIGHT];
layout (std430, set = 0, binding = 14) buffer offsetBufferSSBO {
    Offset offsets;
} offsetsData[NB_PRIMITIVE_TYPES*MAX_FRAMES_IN_FLIGHT];
layout (std430, set = 0, binding = 15) buffer ObjectTypesSSBO {
	int types[];
} objectTypes[MAX_FRAMES_IN_FLIGHT];
layout (std430, set = 0, binding = 16) buffer outputVertexSSBO {
    Vertex vertices[];
} outputVertices[MAX_FRAMES_IN_FLIGHT];
layout (std140, set = 0, binding = 17) uniform UniformBufferObject {
	AABB frustrum;			
	uint nbObjectTypes;
	uint gridCellCount[5];    
    vec3 gridCellSize[5];
    vec3 nbCellsPerRow[5];    
    vec3 gridSize[5];   
    vec3 gridPos[5];
} ubo[MAX_FRAMES_IN_FLIGHT];
layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
bool intersects (AABB first, AABB second) {
    float hx1 = first.size.x * 0.5;
    float hy1 = first.size.y * 0.5;
    float hz1 = first.size.z * 0.5;
    float hx2 = second.size.x * 0.5;
    float hy2 = second.size.y * 0.5;
    float hz2 = second.size.z * 0.5;
    //Check the mins and max medians positions.
    float minX1 = first.center.x - hx1;
    float minX2 = second.center.x - hx2;
    float minY1 = first.center.y - hy1;
    float minY2 = second.center.y - hy2;
    float minZ1 = first.center.z - hz1;
    float minZ2 = second.center.z - hz2;
    float maxX1 = first.center.x + hx1;
    float maxX2 = second.center.x + hx2;
    float maxY1 = first.center.y + hy1;
    float maxY2 = second.center.y + hy2;
    float maxZ1 = first.center.z + hz1;
    float maxZ2 = second.center.z + hz2;
    //If the medians overlap, our two boxes intersects.
    for (int i = 0; i < 3; i++) {
        if (i == 0) {
            if (minX1 > maxX2 || maxX1 < minX2)
                return false;
        } else if (i == 1) {
            if (minY1 > maxY2 || maxY1 < minY2)
                return false;
        } else {
            if (minZ1 > maxZ2 || maxZ1 < minZ2)
                return false;
        }
    }
    return true;
}
bool hasNeightbour(ivec3 pos, int lod, uint axe) {
    vec3 offset;
    if (axe == 0) {
        offset = ivec3(pos.x - ubo[pc.currentFrame].gridCellSize[lod].x, pos.y, pos.z);
    } else if (axe == 1) {
        offset = ivec3(pos.x + ubo[pc.currentFrame].gridCellSize[lod].x, pos.y, pos.z);
    } else if (axe == 2) {
        offset = ivec3(pos.x, pos.y - ubo[pc.currentFrame].gridCellSize[lod].y, pos.z);
    } else if (axe == 3) {
        offset = ivec3(pos.x, pos.y + ubo[pc.currentFrame].gridCellSize[lod].y, pos.z);
    } else if (axe == 4) {
        offset = ivec3(pos.x, pos.y, pos.z - ubo[pc.currentFrame].gridCellSize[lod].z);
    } else {
        offset = ivec3(pos.x, pos.y, pos.z + ubo[pc.currentFrame].gridCellSize[lod].z);
    }
    float gridEndX = ubo[pc.currentFrame].gridSize[lod].x * ubo[pc.currentFrame].gridCellSize[lod].x;
    float gridEndY = ubo[pc.currentFrame].gridSize[lod].y * ubo[pc.currentFrame].gridCellSize[lod].y;
    float gridEndZ = ubo[pc.currentFrame].gridSize[lod].z * ubo[pc.currentFrame].gridCellSize[lod].z;
    float gridStartX = ubo[pc.currentFrame].gridPos[lod].x * ubo[pc.currentFrame].gridCellSize[lod].x;
    float gridStartY = ubo[pc.currentFrame].gridPos[lod].y * ubo[pc.currentFrame].gridCellSize[lod].y;
    float gridStartZ = ubo[pc.currentFrame].gridPos[lod].z * ubo[pc.currentFrame].gridCellSize[lod].z;
    int cellId = int(floor(offset.x / ubo[pc.currentFrame].gridCellSize[lod].x) + floor(offset.y / ubo[pc.currentFrame].gridCellSize[lod].y) * ubo[pc.currentFrame].nbCellsPerRow[lod].x + floor(offset.z / ubo[pc.currentFrame].gridCellSize[lod].z) * ubo[pc.currentFrame].nbCellsPerRow[lod].y);
    if (offset.x < gridStartX || offset.y < gridStartY || offset.z < gridStartZ
        || offset.x >= gridEndX || offset.y >= gridEndY || offset.z >= gridEndZ
        || cellId  >= ubo[pc.currentFrame].gridCellCount[lod] || inputGridBuffer.grid[cellId].clusterId == -1) {
        return false;
    }
    bool hasNVoxel = false;
    /*int stack[32];
    int sp = 0;
    stack[sp++] = inputClustersBuffer.clusters[inputGridBuffer.grid[cellId].clusterId].id;
    while (sp > 0) {
        uint id = stack[sp--];
        Cluster n = inputClustersBuffer.clusters[id];
        if (!intersects(ubo[pc.currentFrame].frustrum, n.volume)) {
            continue;
        }
        if (n.leaf == 1) {
            if (n.lod == 0) {
                for (uint m = 0; m < n.meshletCount && !hasNVoxel; m++) {
                    if (inputMeshlet.meshlets[n.meshletOffset+m].voxel == 1) {
                        hasNVoxel = true;
                    }
                }
            }                               
        } else {
            for (uint c = 0; c < 8; c++) {
                stack[sp++] = n.children[c];
            }
        } 
    }*/
    return hasNVoxel;
}
void setVisibleMeshletsFromBox(AABB frustrum, int lod, Object object, SubMesh sm, uint f, uint materialId) {   
    //debugPrintfEXT("set visible mesh shader");
        
    
    //Ballayage de la grille dans la zone visible.
    /*debugPrintfEXT("current frame : %f %f %f %f %f %f %f %f %f %f %f %i", startx, starty, startz, endx, endy, endz, ubo[pc.currentFrame].gridCellSize[lod].x, ubo[pc.currentFrame].gridCellSize[lod].y, ubo[pc.currentFrame].gridCellSize[lod].z,
    ubo[pc.currentFrame].nbCellsPerRow[lod].x, ubo[pc.currentFrame].nbCellsPerRow[lod].y, ubo[pc.currentFrame].gridCellCount[lod]);
    //debugPrintfEXT("Rendering type : %i", object.renderingType);*/
    float gridEndX = ubo[pc.currentFrame].gridSize[lod].x * ubo[pc.currentFrame].gridCellSize[lod].x;
    float gridEndY = ubo[pc.currentFrame].gridSize[lod].y * ubo[pc.currentFrame].gridCellSize[lod].y;
    float gridEndZ = ubo[pc.currentFrame].gridSize[lod].z * ubo[pc.currentFrame].gridCellSize[lod].z;
    float gridStartX = ubo[pc.currentFrame].gridPos[lod].x * ubo[pc.currentFrame].gridCellSize[lod].x;
    float gridStartY = ubo[pc.currentFrame].gridPos[lod].y * ubo[pc.currentFrame].gridCellSize[lod].y;
    float gridStartZ = ubo[pc.currentFrame].gridPos[lod].z * ubo[pc.currentFrame].gridCellSize[lod].z;
    //debugPrintfEXT("grid limits : %f %f %f", ubo[pc.currentFrame].gridPos[lod].x, ubo[pc.currentFrame].gridPos[lod].y, ubo[pc.currentFrame].gridPos[lod].z);
    
    for (uint i = 0; i < ubo[pc.currentFrame].gridCellCount[lod]; i++) {
        //Root.   
        //debugPrintfEXT("cluster count : %i ", inputGridBuffer.grid[i].clusterCount);
        if (inputGridBuffer.grid[i].clusterId != -1 
            && intersects(inputGridBuffer.grid[i].volume, frustrum)) {
            /*if (inputGridBuffer.grid[i].clusterCount > 0)
            debugPrintfEXT("volume : %i,%i", inputGridBuffer.grid[i].clusterOffset, inputGridBuffer.grid[i].clusterCount);*/
            for (uint j = 0; j < inputGridBuffer.grid[i].clusterCount; j++) {                
                Cluster n = inputClustersBuffer.clusters[inputGridBuffer.grid[i].clusterOffset+j];
                //if (inputGridBuffer.grid[i].clusterOffset > 0)
                
                if (!intersects(frustrum, n.volume)) {
                    //debugPrintfEXT("intersects!");
                    continue;
                }   
                //debugPrintfEXT("lod : %i, smid : %i, %i", n.lod, n.submeshId, sm.id);                 
                if (n.lod == lod && n.submeshId == sm.id) { 
                    //Cluster de modèle 3D visible : On ajoute ce cluster aux clusters visible.
                    //debugPrintfEXT("Rendering type : %i", object.renderingType);
                    if (object.renderingType == 0) {  
                        //debugPrintfEXT("Primitive type : %i", sm.primitiveType);
                        //debugPrintfEXT("cluster visible");
                        uint clusterOffset = atomicAdd(offsetsData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.clusterOffset, 1);                        
                        outputClusters[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].clusters[clusterOffset] = n;    
                        uint taskDataOffset = inputMaterialData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId].taskOffset;                                
                        atomicAdd(outputTaskData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskData[taskDataOffset].meshDrawCommand.groupYCount, 1); 
                        /*if ( n.meshletCount > 0)
                            debugPrintfEXT("leaf, meshlet offset, meshlet count count : %i, %i %i", n.leaf, n.meshletOffset, n.meshletCount);*/
                        for (uint m = 0; m < n.meshletCount; m++) {
                            inputMeshlet.meshlets[n.meshletOffset+m].rendered = 0;
                        }
                        //Heightmap.                            
                    } /*else if (object.renderingType == 1) {
                        uint count = offsetsData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.offsetVertex - offsetsData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.previousOffsetVertex;
                        //Si on dépasse ou on arrive au dernier on créé une nouvelle tâche.
                        if (count + 4 >= MAX_VERTICES 
                            || (count + 4) / 4 * 2 >= MAX_PRIMITIVES) {                                                                
                            TaskData taskData; 
                            MeshDrawCommand meshDrawCommand;                        
                            meshDrawCommand.groupXCount = 1;
                            meshDrawCommand.groupYCount = 1;
                            meshDrawCommand.groupZCount = 1; 
                            taskData.meshDrawCommand = meshDrawCommand;                      
                            taskData.vertexOffset = offsetsData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.previousOffsetVertex;
                            uint taskDataOffset = atomicAdd(outputTaskCount[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskCount, 1);
                            inputMaterialData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId].taskOffset = taskDataOffset;
                            outputTaskData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskData[taskDataOffset] = taskData; 
                            offsetsData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.previousOffsetVertex = offsetsData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.offsetVertex;                    
                        }   
                        //Sommets visible : on les génères.
                        uint taskDataOffset = inputMaterialData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId].taskOffset;
                        TaskData taskData = outputTaskData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskData[taskDataOffset];
                        for (uint h = 0; h < 4; h++) {
                            uint offset = atomicAdd(offsetsData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.offsetVertex, 1); 
                            outputVertices[pc.currentFrame].vertices[offset] = inputVertices[sm.primitiveType].vertices[sm.vertexOffset+h];
                            taskData.vertexCount++;
                        }
                        count = offsetsData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.offsetVertex - offsetsData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.previousOffsetVertex;                                    
                        TaskData task = outputTaskData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskData[taskDataOffset];
                        task.vertexCount = count;
                        task.primitiveCount = count / 4 * 2;
                        outputTaskData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskData[taskDataOffset] = task;
                        //Voxel. 
                    } else {
                        //Voxel visible : on le génère.
                        //if (!hasNeightbour(ivec3(x, y, z), lod, f)) {                                       
                            uint count = offsetsData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.offsetVertex - offsetsData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.previousOffsetVertex;
                            //Si on dépasse ou on arrive au dernier on créé une nouvelle tâche.
                            if (count + 4 >= MAX_VERTICES 
                                || (count + 4) / 4 * 2 >= MAX_PRIMITIVES) {                        
                                TaskData taskData; 
                                MeshDrawCommand meshDrawCommand;                        
                                meshDrawCommand.groupXCount = 1;
                                meshDrawCommand.groupYCount = 1;
                                meshDrawCommand.groupZCount = 1; 
                                taskData.meshDrawCommand = meshDrawCommand;                                                             
                                taskData.vertexOffset = offsetsData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.previousOffsetVertex;
                                uint taskDataOffset = atomicAdd(outputTaskCount[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskCount, 1);
                                outputTaskData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskData[taskDataOffset] = taskData; 
                                offsetsData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.previousOffsetVertex = offsetsData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.offsetVertex;  
                                inputMaterialData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId].taskOffset = taskDataOffset;                       
                            }   
                            uint taskDataOffset = inputMaterialData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId].taskOffset;
                            //Sommets visible : on les génères.
                            TaskData taskData = outputTaskData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskData[taskDataOffset];
                            for (uint h = 0; h < 4; h++) {
                                uint offset = atomicAdd(offsetsData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.offsetVertex, 1); 
                                outputVertices[pc.currentFrame].vertices[offset] = inputVertices[sm.primitiveType].vertices[sm.vertexOffset+h];
                                taskData.vertexCount++;
                            }
                            count = offsetsData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.offsetVertex - offsetsData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.previousOffsetVertex;                                    
                            TaskData task = outputTaskData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskData[taskDataOffset];
                            task.vertexCount = count;
                            task.primitiveCount = count / 4 * 2;
                            outputTaskData[sm.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskData[taskDataOffset] = task;
                        //}    
                    }*/
                }                 
            }
        }
    }
}
void main() {
    //debugPrintfEXT("nb object types : %i, %i, %i",gl_GlobalInvocationID.x, gl_GlobalInvocationID.y, gl_GlobalInvocationID.z);
    memoryBarrier();
    //SubMesh subMesh = inputSubmeshesBuffer.subMeshes[gl_GlobalInvocationID.x];
    Object object = inputObjectBuffer.objects[gl_GlobalInvocationID.x];
	uint materialId = gl_GlobalInvocationID.y;
	uint primitiveType = gl_GlobalInvocationID.z;

	//debugPrintfEXT("nb object types : %v3f, %v3f, %i",ubo[pc.currentFrame].frustrum.center, ubo[pc.currentFrame].frustrum.size, ubo[pc.currentFrame].nbObjectTypes);
	
	for (uint t = 0; t < ubo[pc.currentFrame].nbObjectTypes; t++) {
	    //debugPrintfEXT("type : %i,%i", t, object.type );
        //Modèles 3D. (Regroupement par instances)
		if (object.type == objectTypes[pc.currentFrame].types[t] && intersects(object.globalBounds, ubo[pc.currentFrame].frustrum)) {
		    
            //debugPrintfEXT("Object in frustrum");			
            //Regroupement des données par matériaux et par type de primitive et par pipeline (Batching) et culling.
            for (uint s = 0; s < object.nbSubMeshes; s++) {                    
                SubMesh subMesh = inputSubmeshesBuffer.subMeshes[object.subMeshesOffset+s];             
                if (subMesh.materialId == materialId 
                    && inputMaterialData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId].reflectable != 1
                    && inputMaterialData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId].refractable != 1
                    && subMesh.primitiveType == primitiveType 
                    && intersects(subMesh.globalBounds, ubo[pc.currentFrame].frustrum)) {
                    //debugPrintfEXT("submesh in frustrum %i", s);
                    float dist = distance(ubo[pc.currentFrame].frustrum.center, subMesh.globalBounds.center);
                    float lodStep = 20.0;
                    int lod = clamp(int(dist / lodStep), 0, 4);
                    subMesh.lodLevel = lod;
                    if (object.renderingType == 0) {
                        //Matériel instanciable.
                        if (inputMaterialData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId].instanceGroupId != -1) {
                            //Nouvelle instance de matériel/primitive visible = nouvelle tâche et on enregistre l'offset de la tâche,
                            //pour les instances visibles suivantes.
                            /*if(inputMaterialData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId].vertsInstanceSet == 0) {
                                    
                                inputMaterialData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId].vertsInstanceSet = 1;
                                uint taskDataOffset = atomicAdd(outputTaskCount[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskCount, 1);
                                uint instanceId = atomicAdd(offsetsData[subMesh.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.instanceOffset, 1);
                                
                                inputMaterialData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId].taskOffset = taskDataOffset;
                                MeshDrawCommand meshDrawCommand;
                                meshDrawCommand.groupXCount = 0;
                                meshDrawCommand.groupYCount = 0;
                                meshDrawCommand.groupZCount = 8;
                                TaskData taskData;
                                taskData.baseInstance = instanceId;
                                taskData.vertexCount = 0;
                                taskData.clusterOffset = offsetsData[subMesh.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.clusterOffset;
                                taskData.meshDrawCommand = meshDrawCommand; 
                                MaterialData material = inputMaterialData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId];
                                material.materialId = materialId;
                                outputTaskData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskData[taskDataOffset] = taskData;
                                //outputMaterialData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[instanceId] = material;
                                uint offsetInOutputMeshData = atomicAdd(offsetsData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.submeshOffset, 1);
                                outputMeshData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].meshData[instanceId]  = subMesh;
                                setVisibleMeshletsFromBox(ubo[pc.currentFrame].frustrum, lod, object, subMesh, s, materialId);
                            }
                            uint taskDataOffset = inputMaterialData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId].taskOffset;
                            TaskData taskData = outputTaskData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskData[taskDataOffset]; 
                            uint instanceId = taskData.baseInstance + taskData.meshDrawCommand.groupXCount;
                            ModelData modelData = inputModelData.modelData[object.modelDataOffset];
                            outputModelData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].modelData[instanceId] = modelData;
                            //nombre d'instances + 1.                           
                            outputTaskData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskData[taskDataOffset].meshDrawCommand.groupXCount++;                           
                            setVisibleMeshletsFromBox(ubo[pc.currentFrame].frustrum, lod, object, subMesh, s, materialId);*/
                        //Matériel non instanciable.                                               
                        } else {                        
                            uint offsetTaskData = atomicAdd(outputTaskCount[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskCount, 1);
                            uint instanceId = atomicAdd(offsetsData[subMesh.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.instanceOffset, 1);
                            //uint offsetInOutputMeshData = atomicAdd(offsetsData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.submeshOffset, 1);
                            //debugPrintfEXT("task count %i", offsetTaskData);
                            inputMaterialData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId].taskOffset = offsetTaskData;
                            
                            //debugPrintfEXT("index offset : %i", subMesh.indexOffset);
                            MeshDrawCommand meshDrawCommand;                        
                            meshDrawCommand.groupXCount = 1;
                            meshDrawCommand.groupYCount = 0;
                            meshDrawCommand.groupZCount = 8;
                            TaskData taskData;
                            taskData.baseInstance = instanceId;
                            taskData.vertexCount = 0;
                            taskData.clusterOffset = offsetsData[subMesh.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].offsets.clusterOffset;
                            taskData.meshDrawCommand = meshDrawCommand;
                            //debugPrintfEXT("lod infos : %i, %i",subMesh.lodLevel[lod].index_offset,subMesh.lodLevel[lod].index_count);
                            //debugPrintfEXT("instance base %i", instanceBase); 
                            outputTaskData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskData[offsetTaskData] = taskData;
                            //debugPrintfEXT("indirect elements draw command offset : %i", indirectElementsDrawCommandOffset);
                            ModelData modelData = inputModelData.modelData[object.modelDataOffset];
                            //debugPrintfEXT("model data matrix : %v4f\n%v4f\n%v4f\n%v4f", modelData.modelMatrix[0], modelData.modelMatrix[1], modelData.modelMatrix[2], modelData.modelMatrix[3]);
                            //debugPrintfEXT("object data offset : %i",objectDataOffset);
                            outputModelData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].modelData[instanceId] = modelData;
                            //debugPrintfEXT("offsets : %i, %i, %i", objectDataOffset, offsetInOutputMaterial, indirectElementsDrawCommandOffset);
                            MaterialData material = inputMaterialData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId];
                            //debugPrintfEXT("texture id : %i", material.diffuseTextureIndex);
                            material.materialId = materialId;
                            //debugPrintfEXT("culling shader draw id : %i, material id : %i", indirectElementsDrawCommandOffset, materialId);
                            //debugPrintfEXT("instance base : %i", instanceBase);
                            
                            //outputMaterialData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[instanceId] = material;
                            
                            outputMeshData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].meshData[instanceId] = subMesh;
                            //debugPrintfEXT("material datas %v2f", material.uvScale);
                            //debugPrintfEXT("Output Model Matrix : %i\n%v4f\n%v4f\n%v4f\n%v4f",objectDataOffset,outputObjectData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].objectData[objectDataOffset].modelMatrix[0], outputObjectData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].objectData[objectDataOffset].modelMatrix[1], outputObjectData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].objectData[objectDataOffset].modelMatrix[2], outputObjectData[primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].objectData[objectDataOffset].modelMatrix[3]);
                            setVisibleMeshletsFromBox(ubo[pc.currentFrame].frustrum, lod, object, subMesh, s, materialId);
                        }                                                   
                    } /*else { 
                        uint taskOffset = inputMaterialData[subMesh.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId].taskOffset;
                        //Si pas de tâche pour ce matériel on la créé.
                        if (taskOffset == -1) {
                            TaskData taskData; 
                            MeshDrawCommand meshDrawCommand;                        
                            meshDrawCommand.groupXCount = 1;
                            meshDrawCommand.groupYCount = 1;
                            meshDrawCommand.groupZCount = 1; 
                            taskData.meshDrawCommand = meshDrawCommand; 
                            uint taskDataOffset = atomicAdd(outputTaskCount[subMesh.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].taskCount, 1);
                            inputMaterialData[subMesh.primitiveType*MAX_FRAMES_IN_FLIGHT+pc.currentFrame].materialData[materialId].taskOffset = taskDataOffset;  
                        }                       
                        setVisibleMeshletsFromBox(ubo[pc.currentFrame].frustrum, lod, object, subMesh, s, materialId);
                    } */
                }                           
            }
            //Heighmap : Regroupement des tâches par limite de sommets dans ce cas.
        } 
	}
}