#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_ray_query : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_debug_printf : enable
#define MAX_TLAS_STRUCTURES 100
#define MAX_FRAMES_IN_FLIGHT 2
#define MAX_BOUNCES 3
#define NB_CASCADES 4
struct DirectionnalLight {
    int id;
    vec3 dir;
    vec4 color;
    mat4 lightSpace[NB_CASCADES+1];
};
struct PointLight {
    int id;
    vec3 position;
    vec4 color;
    mat4 lightSpace[6];
};
layout(binding = 0, set = 0) uniform CameraProperties {
    mat4 viewInverse;
    mat4 projInverse;    
} cam[MAX_FRAMES_IN_FLIGHT];
layout(binding = 1, set = 0, rgba8) uniform image2D image[MAX_FRAMES_IN_FLIGHT];
layout(binding = 2, set = 0) buffer DirectionnalLightSSBO {
    DirectionnalLight directionnalLights[];
};
layout(binding = 3, set = 0) buffer PointLightSSBO {
    PointLight pointLights[];
}; 
layout(binding = 4, set = 0, rgba8) uniform image2D rasterImage; 
layout(binding = 5, set = 0) uniform accelerationStructureEXT globalAS;
layout(binding = 6, set = 0) uniform accelerationStructureEXT localAS[MAX_TLAS_STRUCTURES];

layout (push_constant) uniform PushConstant {
    uint currentFrame;
    uint directionnalLightCount;
    uint pointLightCount;
    uint hasGeometry;
} pc;
struct Material {   
    /*vec2 uvScale;
    vec2 uvOffset;*/
    uint diffuseTextureIndex;
    uint specularTextureIndex;
    uint normalTextureIndex;
    uint metalnessTextureIndex;
    uint roughnessTextureIndex;
    uint aoTextureIndex;
    uint emissiveTextureIndex;
    uint materialType;
    uint materialSet;   
    uint nbVertices;
    uint nbIndexes;
    int instanceGroupId;
    uint vertsInstanceSet;
    uint materialId;
    uint nbBuffers;  
    int reflectable;
    int refractable;
    int opaque;  
};
struct TransportRayPayload {
    bool lastBounce;
    int rayType;
    vec4 finalColor;
    vec4 primaryColor;
    vec4 secondaryColor;
    vec4 transmitionColor;
    vec4 reflectColor;
    vec4 refractColor;
    vec3 origin;
    vec3 direction;
    vec3 R;
    vec3 T; 
    bool reflectable;
    bool refractable;
    bool transmissive;  
    int localASID; 
    vec3 normal;
    Material parentMaterial; 
    vec4 localLightning;
    vec3 lightPos;
    int lightId;        
    vec4 lightColor; 
    vec4 shadowColor; 
    mat4 dirLightSpace[NB_CASCADES+1];
    mat4 pointLightSpace[6];
};
layout(location = 0) rayPayloadEXT TransportRayPayload transport; // ray generation
void main() {
    //debugPrintfEXT("current frame index : %i", pc.currentFrame);
    transport.lastBounce = false;
    transport.finalColor = vec4(0); 
    transport.secondaryColor = vec4(1);
    transport.primaryColor = vec4(1);   
    const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
    const vec2 inUV = pixelCenter/vec2(gl_LaunchSizeEXT.xy);
    vec2 d = inUV * 2.0 - 1.0;

    vec4 origin = cam[pc.currentFrame].viewInverse * vec4(0,0,0,1);
    vec4 target = cam[pc.currentFrame].projInverse * vec4(d.x, d.y, 1, 1) ;
    vec4 direction = cam[pc.currentFrame].viewInverse*vec4(normalize(target.xyz), 0) ;

    float tmin = 0.001;
    float tmax = 10000.0;
    transport.rayType = 0;
    if (pc.hasGeometry == 0) {
        vec4 color = imageLoad(rasterImage, ivec2(gl_LaunchIDEXT.xy));
        imageStore(rasterImage, ivec2(gl_LaunchIDEXT.xy), color);
    } else {
        traceRayEXT(globalAS, gl_RayFlagsOpaqueEXT, 0xff, 0, 0, 0, origin.xyz, tmin, direction.xyz, tmax, 0);   
        uint i = 0;    
        while (i < MAX_BOUNCES && !transport.lastBounce) {
            //Objet translucide touché.
            vec3 hitpoint = transport.origin;
            if (transport.transmissive) {
                transport.rayType = 1;
                traceRayEXT(localAS[transport.localASID], gl_RayFlagsNoneEXT, 0xff, 0, 0, 0, hitpoint.xyz, tmin, transport.direction, tmax, 0);            
            }   
            //Objet translucide réflectable touché traçage du rayon de rélfection.
            if (transport.reflectable) {
                transport.rayType = 2;
                traceRayEXT(localAS[transport.localASID], gl_RayFlagsNoneEXT, 0xff, 0, 0, 0, hitpoint.xyz, tmin, transport.direction, tmax, 0);            
            }      
            //Objet translucide réfractable touché traçage du rayon de réfraction.
            if (transport.refractable) {
                transport.rayType = 3;
                traceRayEXT(localAS[transport.localASID], gl_RayFlagsNoneEXT, 0xff, 0, 0, 0, hitpoint.xyz, tmin, transport.T, tmax, 0);            
            }
            //Calcul et projection du shadow ray (pour rayons déviés ou non)
            for (uint l = 0; l < pc.directionnalLightCount; l++) {
                vec3 invLightDir = -directionnalLights[l].dir;
                transport.rayType = 4;
                transport.lightId = directionnalLights[l].id;
                transport.lightColor = directionnalLights[l].color;
                transport.dirLightSpace = directionnalLights[l].lightSpace;                        
                traceRayEXT(localAS[transport.localASID], gl_RayFlagsOpaqueEXT, 0xff, 0, 0, 0, hitpoint.xyz, tmin, invLightDir.xyz, tmax, 0);           
            }            
            for (uint l = 0; l < pc.pointLightCount; l++) {
                vec3 invLightDir = transport.origin - pointLights[l].position;
                transport.rayType = 5;
                transport.lightId = pointLights[l].id;
                transport.lightPos = pointLights[l].position;
                transport.lightColor = pointLights[l].color;
                transport.pointLightSpace = pointLights[l].lightSpace;            
                traceRayEXT(localAS[transport.localASID], gl_RayFlagsOpaqueEXT, 0xff, 0, 0, 0, hitpoint.xyz, tmin, invLightDir.xyz, tmax, 0);                
            }
            vec4 finalColor = vec4(0);
            if (transport.reflectable)
                finalColor += transport.reflectColor;

            if (transport.refractable)
                finalColor += transport.refractColor;
            if (transport.transmissive)
                finalColor += transport.transmitionColor;

            finalColor *= transport.localLightning; 

            transport.secondaryColor += finalColor;
            if (!transport.reflectable &&
                !transport.refractable &&
                !transport.transmissive)
            {
                transport.lastBounce = true;
            }
            i++; 
        }    
        transport.finalColor = transport.primaryColor * transport.secondaryColor;
        /*if (payload.color.r != 0 || payload.color.g != 0 || payload.color.b != 0 || payload.color.a != 0) {
            if (payload.color.r > 1 || payload.color.g > 1 || payload.color.b > 1 || payload.color.a > 1) {        
                //debugPrintfEXT("color : %v4f", payload.color);
            } else {
                //debugPrintfEXT("color : %v4f", payload.color);
            }
        }*/    
        imageStore(image[pc.currentFrame], ivec2(gl_LaunchIDEXT.xy), transport.finalColor);
    }
}