#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_ray_query : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_debug_printf : enable
#define MAX_TLAS_STRUCTURES 100
#define MAX_FRAMES_IN_FLIGHT 2
layout(binding = 0, set = 0) uniform CameraProperties {
    mat4 viewInverse;
    mat4 projInverse;    
} cam[MAX_FRAMES_IN_FLIGHT];
layout(binding = 1, set = 0, rgba8) uniform image2D image[MAX_FRAMES_IN_FLIGHT];
layout(binding = 2, set = 0) uniform accelerationStructureEXT topLevelAS[MAX_TLAS_STRUCTURES];
layout (push_constant) uniform PushConstant {
    uint currentFrame;
    uint tlasCount;
} pc;
// Dans le shader commun
struct RayPayload {
    vec4 color;
};
layout(location = 0) rayPayloadEXT RayPayload payload; // ray generation
void main() {
    //debugPrintfEXT("current frame index : %i", pc.currentFrame);
    const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
    const vec2 inUV = pixelCenter/vec2(gl_LaunchSizeEXT.xy);
    vec2 d = inUV * 2.0 - 1.0;

    vec4 origin = cam[pc.currentFrame].viewInverse * vec4(0,0,0,1);
    vec4 target = cam[pc.currentFrame].projInverse * vec4(d.x, d.y, 1, 1) ;
    vec4 direction = cam[pc.currentFrame].viewInverse*vec4(normalize(target.xyz), 0) ;

    float tmin = 0.001;
    float tmax = 10000.0;
    for (uint i = 0; i < pc.tlasCount; i++) {
        traceRayEXT(topLevelAS[i], gl_RayFlagsOpaqueEXT, 0xff, 0, 0, 0, origin.xyz, tmin, direction.xyz, tmax, 0);
    }
    if (payload.color.r != 0 || payload.color.g != 0 || payload.color.b != 0 || payload.color.a != 0)
        debugPrintfEXT("color : %v4f", payload.color);
    imageStore(image[pc.currentFrame], ivec2(gl_LaunchIDEXT.xy), payload.color);
}