#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_ray_query : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_debug_printf : enable
#define MAX_TLAS_STRUCTURES 100
#define MAX_FRAMES_IN_FLIGHT 2
#define MAX_BOUNCES 3
struct DirectionnalLight {
    uint id;
    vec3 dir;
    vec3 color;
    mat4 lightSpace;
};
struct PointLight {
    uint id;
    vec3 position;
    vec3 color;
    mat4 lightSpace[6];
};
layout(binding = 0, set = 0) uniform CameraProperties {
    mat4 viewInverse;
    mat4 projInverse;    
} cam[MAX_FRAMES_IN_FLIGHT];
layout(binding = 1, set = 0, rgba8) uniform image2D image[MAX_FRAMES_IN_FLIGHT];
layout(binding = 2, set = 0) buffer DirectionnalLightSSBO {
    DirectionnalLight directionnalLights[];
};
layout(binding = 3, set = 0) buffer PointLightSSBO {
    PointLight pointLights[];
}; 
layout(binding = 4, set = 0) uniform accelerationStructureEXT globalAS;
layout(binding = 5, set = 0) uniform accelerationStructureEXT localAS[MAX_TLAS_STRUCTURES];
layout (push_constant) uniform PushConstant {
    uint currentFrame;
    uint directionnalLightCount;
    uint ponctualLightCount;
} pc;
struct TransportRayPayload {
    bool lastBounce;
    int raytype;    
    vec4 finalColor;
    vec4 primaryColor;
    vec4 secondaryColor;
    vec4 transmitionColor;
    vec4 reflectColor;
    vec4 refractColor;
    vec3 origin;
    vec3 direction;
    vec3 R;
    vec3 T; 
    bool transmissive;
    bool reflectable;
    bool refractable;  
    int localADID; 
    vec3 normal;
    Material parentMaterial; 
};
struct ShadowRayPayload {
    vec4 localLightning;
    vec3 lightPos;
    vec4 lightPos;
    int lightId;        
    vec4 lightColor; 
    vec4 shadowColor; 
    mat4 lightSpace[6];
    vec3 normal;
    Material parentMaterial;
};
layout(location = 0) rayPayloadEXT TransportRayPayload transportpayload; // ray generation
layout(location = 1) rayPayloadEXT ShadowRayPayload shadow; // shadow ray generation
void main() {
    //debugPrintfEXT("current frame index : %i", pc.currentFrame);
    transpostpayload.lastBounce = false;
    transport.finalColor = vec4(0); 
    transport.secondaryColor = vec4(1);
    transport.pirmaryColor = vec4(0);   
    const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
    const vec2 inUV = pixelCenter/vec2(gl_LaunchSizeEXT.xy);
    vec2 d = inUV * 2.0 - 1.0;
    payLoad.rayType = 0;

    origin = cam[pc.currentFrame].viewInverse * vec4(0,0,0,1);
    vec4 target = cam[pc.currentFrame].projInverse * vec4(d.x, d.y, 1, 1) ;
    direction = cam[pc.currentFrame].viewInverse*vec4(normalize(target.xyz), 0) ;

    float tmin = 0.001;
    float tmax = 10000.0;
    transport.raytype = 0;
    traceRayEXT(globalAS, gl_RayFlagsOpaqueEXT, 0xff, 0, 0, 0, origin.xyz, tmin, direction.xyz, tmax, 0);   
    uint i = 0;    
    while (i < MAX_BOUNCES && !transportpayload.lastBounce) {
        //Objet translucide touché.
        if (transport.transmissive) {
            transport.rayType = 1;
            traceRayEXT(localAS[payload.localASID], gl_RayFlagsNoneEXT, 0xff, 0, 0, 0, transport.origin, tmin, transport.direction, tmax, 0);            
        }   
        //Objet translucide réflectable touché traçage du rayon de rélfection.
        if (transport.reflectalbe) {
            transport.rayType = 2;
            traceRayEXT(localAS[payload.localASID], gl_RayFlagsNoneEXT, 0xff, 0, 0, 0, transport.origin, tmin, transport.direction, tmax, 0);            
        }      
        //Objet translucide réfractable touché traçage du rayon de réfraction.
        if (payload.refractable) {
            transport.raytype = 3;
            traceRayEXT(localAS[payload.localASID], gl_RayFlagsNoneEXT, 0xff, 0, 0, 0, transport.origin, tmin, transport.T, tmax, 0);            
        }
        shadow.normal = transport.normal;
        shadow.parentMaterial = transport.parentMaterial;
        //Calcul et projection du shadow ray (pour rayons déviés ou non)
        for (uint l = 0; l < pc.directionnalLightCount; l++) {
            vec3 invLightDir = -directionnalLights[l].dir;
            transport.rayType = 4;
            shadowpayload.lightId = directionnalLights[l].id;
            shadowpayLoad.lightColor = directionnalLights[l].color;
            shadowpayLoad.lightSpace[0] = directionnalLights[l].lightSpace;                        
            traceRayEXT(localAS[payload.localASID], gl_RayFlagsOpaqueEXT, 0xff, 0, 0, 0, transportpay.origin, tmin, invLightdir.xyz, tmax, 1);           
        }
        
        for (uint l = 0; l < pc.pointLightCount; l++) {
            vec3 invLightDir = payload.origin - pointLights[l].position;
            transport.rayType = 5;
            shadowpayLoad.lightId = pointLights[l].id;
            shadowpayLoad.lightPos = pointLights[l].position;
            shadowpayload.lightColor = pointLights[l].color;
            shadowpayLoad.lightSpace = pointLights[l].lightSpace;            
            traceRayEXT(localAS[payload.localASID], gl_RayFlagsOpaqueEXT, 0xff, 0, 0, 0, transposrt.origin, tmin, invLightdir.xyz, tmax, 1);                
        }
        vec3 finalColor = vec3(0);
        if (transport.reflectable)
            transport.finalColor += reflect.color;

        if (transport.refractable)
            transport.finalColor += refract.color;

        if (transport.transmissive)
            transport.finalColor += transmit.color;

        vec4 finalColor *= shadow.localLightning; 

        transport.secondaryColor += finalColor;
        if (!transport.reflectable &&
            !transport.refractable &&
            !transport.transmissive)
        {
            transport.lastBounce = true;
        }
        i++; 
    }    
    transport.finalColor = transport.primaryColor * transport.secondaryColor;
    if (payload.color.r != 0 || payload.color.g != 0 || payload.color.b != 0 || payload.color.a != 0) {
        if (payload.color.r > 1 || payload.color.g > 1 || payload.color.b > 1 || payload.color.a > 1) {        
            //debugPrintfEXT("color : %v4f", payload.color);
        } /*else {
            //debugPrintfEXT("color : %v4f", payload.color);
        }*/
    }    
    imageStore(image[pc.currentFrame], ivec2(gl_LaunchIDEXT.xy), transport.finalColor);
}